/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package main.data;

@SuppressWarnings("all")
/** This is a message. */
@org.apache.avro.specific.AvroGenerated
public interface messageProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"messageProtocol\",\"namespace\":\"main.data\",\"doc\":\"This is a message.\",\"name\":\"Message\",\"types\":[{\"type\":\"record\",\"name\":\"message\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"content\",\"type\":\"string\"},{\"name\":\"timestmp\",\"type\":\"long\"}]}],\"messages\":{\"sendMessage\":{\"doc\":\"message rpc test!!\",\"request\":[{\"name\":\"message\",\"type\":\"message\"}],\"response\":\"message\"}}}");
  /**
   * message rpc test!!
   */
  message sendMessage(message message) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  /** This is a message. */
  public interface Callback extends messageProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = messageProtocol.PROTOCOL;
    /**
     * message rpc test!!
     * @throws java.io.IOException The async call could not be completed.
     */
    void sendMessage(message message, org.apache.avro.ipc.Callback<message> callback) throws java.io.IOException;
  }
}